import { TreePine, Droplets, Factory, Anchor } from "lucide-react";

export const DOMAINS = [
  {
    id: "wilk",
    name: "Wilk",
    region: "Białowieża",
    icon: TreePine,
    coordinates: [23.866, 52.716] as [number, number],
    color: "text-emerald-400",
    bgHover: "hover:bg-emerald-400/10",
    borderHover: "hover:border-emerald-400/50",
    activeBg: "bg-emerald-500/10",
    activeBorder: "border-emerald-500/30",
    activeText: "text-emerald-100",
    activeShadow: "shadow-[0_0_8px_#10b981]",
    activeBullet: "bg-emerald-500",
    description: "Crisis: Spruce bark beetle (Ips typographus) infestations exacerbated by climate droughts, triggering highly destructive 'salvage logging' policies. Ancient Method: Dead-Wood Ecology and draft-horse extraction to prevent soil compaction.",
    metrics: { nodes: 142, flux: "3.2TB/s", co2: "92.1%" },
    recommendation: "The 'Silent Canopy' Protocol: Fusing high-orbit multi-spectral satellite data (Sentinel-2) to detect early 'Green Attacks' via water-stress signatures. At ground level, offline AudioMoth Edge AI sensors listen for the ultrasonic chewing of bark beetles without disturbing Natura 2000 protected birds.",
    promptMsg: "Initiate Silent Canopy Protocol?"
  },
  {
    id: "zubr",
    name: "Żubr",
    region: "Masovia",
    icon: Droplets,
    coordinates: [21.012, 52.229] as [number, number],
    color: "text-blue-400",
    bgHover: "hover:bg-blue-400/10",
    borderHover: "hover:border-blue-400/50",
    activeBg: "bg-blue-500/10",
    activeBorder: "border-blue-500/30",
    activeText: "text-blue-100",
    activeShadow: "shadow-[0_0_8px_#3b82f6]",
    activeBullet: "bg-blue-500",
    description: "Crisis: Severe national freshwater scarcity, rapid snowmelt runoff, and devastating summer droughts due to historical river straightening. Ancient Method: Zastawki (woven-wood weirs) and Beaver-mimicry to slow water flow and recharge aquifers.",
    metrics: { nodes: 87, flux: "1.8TB/s", co2: "70.4%" },
    recommendation: "Hydrological ML processing identifies optimal micro-choke points across thousands of small streams. Biodegradable, IoT-actuated zastawki are dynamically opened/closed by the Central AI based on IMGW rainfall forecasting, turning the country into a massive decentralized water sponge.",
    promptMsg: "Deploy IoT Zastawki Network?"
  },
  {
    id: "dzieciolek",
    name: "Dzięciołek",
    region: "Silesia",
    icon: Factory,
    coordinates: [19.023, 50.264] as [number, number],
    color: "text-amber-400",
    bgHover: "hover:bg-amber-400/10",
    borderHover: "hover:border-amber-400/50",
    activeBg: "bg-amber-500/10",
    activeBorder: "border-amber-500/30",
    activeText: "text-amber-100",
    activeShadow: "shadow-[0_0_8px_#f59e0b]",
    activeBullet: "bg-amber-500",
    description: "Crisis: Toxic coal mining tailing heaps (hałdy) leaching heavy metals into the groundwater and releasing toxic coal dust. Ancient Method: Phytoremediation and topographical terracing.",
    metrics: { nodes: 204, flux: "5.1TB/s", co2: "65.8%" },
    recommendation: "Chemical ML modeling calculates optimal geometric terracing for each specific heap. Autonomous Drone Swarms spray custom bio-mixtures of native hyper-accumulating plants (willows/mustards) and mycorrhizal fungi to biologically lock down the toxins.",
    promptMsg: "Authorize Phytoremediation Swarm?"
  },
  {
    id: "los",
    name: "Łoś",
    region: "Baltic",
    icon: Anchor,
    coordinates: [18.646, 54.352] as [number, number],
    color: "text-cyan-400",
    bgHover: "hover:bg-cyan-400/10",
    borderHover: "hover:border-cyan-400/50",
    activeBg: "bg-cyan-500/10",
    activeBorder: "border-cyan-500/30",
    activeText: "text-cyan-100",
    activeShadow: "shadow-[0_0_8px_#06b6d4]",
    activeBullet: "bg-cyan-500",
    description: "Crisis: Coastal erosion, eutrophication (nitrogen-driven algal blooms), and rusting WWII chemical munitions. Ancient Method: Permeable Baltic willow fascines, glacial boulder reefs, and biological filtration via native bivalves and shoreline reeds.",
    metrics: { nodes: 64, flux: "1.1TB/s", co2: "85.2%" },
    recommendation: "Hydrodynamic ML models simulate winter storm surges to 3D-print mathematically perfect fascine reefs. Autonomous Underwater Vehicles (AUVs) seed these structures with Baltic Blue Mussels (Omułek jadalny) for bio-filtration, while AI-routed pontoons harvest shoreline reeds to extract excess nitrogen.",
    promptMsg: "Deploy Coastal Defense AUVs?"
  },
];
